---
title: "HIV_DATA"
output: html_document
date: "2023-04-28"
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(mice)
library(VIM)

```


```{r Data Processing I}

hiv_data <- read.csv("HealthGymV2_CbdrhDatathon_ART4HIV.csv")

#View initial data summary
summary(hiv_data)

#Check how many ethnic groups there are
summary(as.factor(hiv_data$Ethnic))

#Factorise `Gender`
hiv_data$Gender <- factor(hiv_data$Gender, levels = c(1, 2),
                          labels = c("Male", "Female"))

#Factorise `Ethnicity`
hiv_data$Ethnic <- factor(hiv_data$Ethnic, levels = c(1, 2, 3, 4),
                          labels = c("Asian", "Afro", "Caucasian", "Other"))


#Check if the same patient has the same gender and ethnicity
hiv_data %>% group_by(PatientID) %>%
  summarise(same_gender = n_distinct(Gender) == 1,
            same_ethnicity = n_distinct(Ethnic) == 1) -> check_gender_ethnicity

#Check if there are any FALSE values in these columns - there is none
any(!check_gender_ethnicity$same_gender)
any(!check_gender_ethnicity$same_ethnicity)



#Check if `Timestep` sequences from 0 to 59 by each `PatientID`
check_timepoints <- hiv_data %>%
  group_by(PatientID) %>%
  summarise(is_sequence = all(Timestep == 0:59))

#Check if there are any FALSE values in these columns - there are none
any(!check_timepoints$is_sequence)


#Factorise `PatientID`
hiv_data$PatientID <- factor(hiv_data$PatientID, levels = 0:8915)


#Factorise `Base.Drug.Combo`, `Comp..INI`, `Comp..NNRTI`, `Extra.PI`, `Extra.pk.En`, 
#`VL..M.`, `CD4..M.`, and `Drug..M.`
hiv_data$Base.Drug.Combo <- factor(hiv_data$Base.Drug.Combo, levels = c(0, 1, 2, 3, 4, 5),
                          labels = c("FTC + TDF",
                                     "3TC + ABC",
                                     "FTC + TAF",
                                     "DRV + FTC + TDF",
                                     "FTC + RTVB + TDF",
                                     "Other"))

hiv_data$Comp..INI <- factor(hiv_data$Comp..INI, levels = c(0, 1, 2, 3),
                          labels = c("DTG", "RAL", "EVG", "Not Applied"))

hiv_data$Comp..NNRTI <- factor(hiv_data$Comp..NNRTI, levels = c(0, 1, 2, 3),
                          labels = c("NVP", "EFV", "RPV", "Not Applied"))

hiv_data$Extra.PI <- factor(hiv_data$Extra.PI, levels = c(0, 1, 2, 3, 4, 5),
                          labels = c("DRV", "RTVB", "LPV", "RTV", "ATV", "Not Applied"))


#Rename some variables
hiv_data <- hiv_data %>% rename(Rel_CD4 = Rel.CD4,
                                Base_Drug = Base.Drug.Combo, 
                                INI = Comp..INI,
                                NNRTI = Comp..NNRTI,
                                Extra_PI = Extra.PI,
                                Extra_pk_En = Extra.pk.En,
                                VL_M = VL..M.,
                                CD4_M = CD4..M.,
                                Drug_M = Drug..M.)

#Examine the data frame again
summary(hiv_data)


#Some data cleaning checks:
#The same patient always has the same gender and ethnicity
#The time points always span from 0 to 59 for each patient
#No missing data, apparently -> change the according to the Measurement variables

#Problems in the data:
#There are 4030 time points in total where `Base_Drug` and `Extra_PI` include the medication DRV - we will treat these as one medication intake, and won't 'duplicate' that medication prescription

#There are 2102 time points in total where `Base_Drug` and `Extra_PI` include the medication RTVB - we will treat these as one medication intake, and won't 'duplicate' that medication prescription

#There are 1069 rows where patients took only the "Other" base drug

```


```{r Data Processing II}

#Re-level some variables
hiv_data$Ethnic <- relevel(hiv_data$Ethnic, ref = "Other")
hiv_data$Base_Drug <- relevel(hiv_data$Base_Drug, ref = "Other")
hiv_data$INI <- relevel(hiv_data$INI, ref = "Not Applied")
hiv_data$NNRTI <- relevel(hiv_data$NNRTI, ref = "Not Applied")
hiv_data$Extra_PI <- relevel(hiv_data$Extra_PI, ref = "Not Applied")


#Replace VL, CD4+Rel CD4, and the medications variable values with NAs based on their measurment variables
hiv_data$VL <- apply(hiv_data, 1, function(row) ifelse(row["VL_M"] == 0, NA, row["VL"]))

hiv_data$CD4 <- apply(hiv_data, 1, function(row) ifelse(row["CD4_M"] == 0, NA, row["CD4"]))
hiv_data$Rel_CD4 <- apply(hiv_data, 1, function(row) ifelse(row["CD4_M"] == 0, NA, row["Rel_CD4"]))

hiv_data$Base_Drug <- apply(hiv_data, 1, function(row) ifelse(row["Drug_M"] == 0, NA, row["Base_Drug"]))
hiv_data$INI <- apply(hiv_data, 1, function(row) ifelse(row["Drug_M"] == 0, NA, row["INI"]))
hiv_data$NNRTI <- apply(hiv_data, 1, function(row) ifelse(row["Drug_M"] == 0, NA, row["NNRTI"]))
hiv_data$Extra_PI <- apply(hiv_data, 1, function(row) ifelse(row["Drug_M"] == 0, NA, row["Extra_PI"]))
hiv_data$Extra_pk_En <- apply(hiv_data, 1, function(row) ifelse(row["Drug_M"] == 0, NA, row["Extra_pk_En"]))

#Remove the measurement variables
hiv_data <- hiv_data[, c(-11, -12, -13)]

#Convert VL to float
hiv_data$VL <- as.numeric(hiv_data$VL)

# #Convert CD4 to float
# hiv_data$CD4 <- as.numeric(hiv_data$CD4)
# 
# #Convert Rel_CD4 to float
# hiv_data$Rel_CD4 <- as.numeric(hiv_data$Rel_CD4)
# 
# #Convert Base_Drug to factor
# hiv_data$Base_Drug <- as.factor(hiv_data$Base_Drug)
# 
# #Convert INI to factor
# hiv_data$INI <- as.factor(hiv_data$INI)
# 
# #Convert NNRTI to factor
# hiv_data$NNRTI <- as.factor(hiv_data$NNRTI)
# 
# #Convert Extra_PI to factor
# hiv_data$Extra_PI <- as.factor(hiv_data$Extra_PI)
# 
# #Convert Extra_pk_En to factor
# hiv_data$Extra_pk_En <- as.factor(hiv_data$Extra_pk_En)
# 
# #Convert Gender to factor
# hiv_data$Gender <- as.factor(hiv_data$Gender)
# 
# #Convert Ethnic to factor
# hiv_data$Ethnic <- as.factor(hiv_data$Ethnic)

```


```{r Data Processing III}

#Create separate variables for each medication - Base_Drug
hiv_data$FTC <- as.integer(grepl("FTC", hiv_data$Base_Drug))
hiv_data$FTC <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Base_Drug"]), NA, row["FTC"]))

hiv_data$TDF <- as.integer(grepl("TDF", hiv_data$Base_Drug))
hiv_data$TDF <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Base_Drug"]), NA, row["TDF"]))


hiv_data$TC3 <- as.integer(grepl("3TC", hiv_data$Base_Drug)) 
#Called it TC3, as it's problematic to name a column starting with a number
hiv_data$TC3 <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Base_Drug"]), NA, row["TC3"]))

hiv_data$ABC <- as.integer(grepl("ABC", hiv_data$Base_Drug))
hiv_data$ABC <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Base_Drug"]), NA, row["ABC"]))

hiv_data$TAF <- as.integer(grepl("TAF", hiv_data$Base_Drug))
hiv_data$TAF <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Base_Drug"]), NA, row["TAF"]))

hiv_data$DRV_base <- as.integer(grepl("DRV", hiv_data$Base_Drug))
hiv_data$DRV_base <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Base_Drug"]), NA, row["DRV_base"]))

hiv_data$RTVB_base <- as.integer(grepl("RTVB", hiv_data$Base_Drug))
hiv_data$RTVB_base <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Base_Drug"]), NA, row["RTVB_base"]))

hiv_data$Other_base <- as.integer(grepl("Other", hiv_data$Base_Drug))
hiv_data$Other_base <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Base_Drug"]), NA, row["Other_base"]))
 

#Create separate variables for each medication - INI
hiv_data$DTG <- as.integer(grepl("DTG", hiv_data$INI))
hiv_data$DTG <- apply(hiv_data, 1, function(row) ifelse(is.na(row["INI"]), NA, row["DTG"]))

hiv_data$RAL <- as.integer(grepl("RAL", hiv_data$INI))
hiv_data$RAL <- apply(hiv_data, 1, function(row) ifelse(is.na(row["INI"]), NA, row["RAL"]))

hiv_data$EVG <- as.integer(grepl("EVG", hiv_data$INI))
hiv_data$EVG <- apply(hiv_data, 1, function(row) ifelse(is.na(row["INI"]), NA, row["EVG"]))

hiv_data$Not_applied_INI <- as.integer(grepl("Not Applied", hiv_data$INI))
hiv_data$Not_applied_INI <- apply(hiv_data, 1, function(row) ifelse(is.na(row["INI"]), NA, row["Not_applied_INI"]))


#Create separate variables for each medication - NNRTI
hiv_data$NVP <- as.integer(grepl("NVP", hiv_data$NNRTI))
hiv_data$NVP <- apply(hiv_data, 1, function(row) ifelse(is.na(row["NNRTI"]), NA, row["NVP"]))

hiv_data$EFV <- as.integer(grepl("EFV", hiv_data$NNRTI))
hiv_data$EFV <- apply(hiv_data, 1, function(row) ifelse(is.na(row["NNRTI"]), NA, row["EFV"]))

hiv_data$RPV <- as.integer(grepl("RPV", hiv_data$NNRTI))
hiv_data$RPV <- apply(hiv_data, 1, function(row) ifelse(is.na(row["NNRTI"]), NA, row["RPV"]))

hiv_data$Not_applied_NNRTI <- as.integer(grepl("Not Applied", hiv_data$NNRTI))
hiv_data$Not_applied_NNRTI <- apply(hiv_data, 1, function(row) ifelse(is.na(row["NNRTI"]), NA, row["Not_applied_NNRTI"]))


#Create separate variables for each medication - Extra_PI
hiv_data$DRV_extra_pi <- as.integer(grepl("DRV", hiv_data$Extra_PI))
hiv_data$DRV_extra_pi <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Extra_PI"]), NA, row["DRV_extra_pi"]))

hiv_data$RTVB_extra_pi <- as.integer(grepl("RTVB", hiv_data$Extra_PI))
hiv_data$RTVB_extra_pi <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Extra_PI"]), NA, row["RTVB_extra_pi"]))

hiv_data$LPV <- as.integer(grepl("LPV", hiv_data$Extra_PI))
hiv_data$LPV <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Extra_PI"]), NA, row["LPV"]))

hiv_data$RTV <- as.integer(grepl("RTV", hiv_data$Extra_PI))
hiv_data$RTV <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Extra_PI"]), NA, row["RTV"]))

hiv_data$ATV <- as.integer(grepl("ATV", hiv_data$Extra_PI))
hiv_data$ATV <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Extra_PI"]), NA, row["ATV"]))

hiv_data$Not_applied_extra_pi <- as.integer(grepl("Not Applied", hiv_data$Extra_PI))
hiv_data$Not_applied_extra_pi <- apply(hiv_data, 1, function(row) ifelse(is.na(row["Extra_PI"]), NA, row["Not_applied_extra_pi"]))


#Remove the columns Base_Drug, INI, NNRTI, Extra_PI
hiv_data <- hiv_data[, c(-6, -7, -8, -9)]


#Count the number of rows with 1 in both `DRV_base` and `DRV_extra_pi`
count_drv <- sum(na.omit(hiv_data$DRV_base) == 1 & na.omit(hiv_data$DRV_extra_pi) == 1) #4030 rows

#Count the number of rows with 1 in both `RTVB_base` and `RTVB_extra_pi`
count_rtvb <- sum(na.omit(hiv_data$RTVB_base) == 1 & na.omit(hiv_data$RTVB_extra_pi) == 1) #2102 rows

#Convert the columns to integer type
turn_integer <- c("FTC", "TDF", "TC3", "ABC", "TAF", "DRV_base", "RTVB_base", "Other_base", "DTG", "RAL", "EVG", "Not_applied_INI", "NVP", "EFV", "RPV", "Not_applied_NNRTI", "DRV_extra_pi", "RTVB_extra_pi", "LPV", "RTV", "ATV", "Not_applied_extra_pi", "Extra_pk_En")

hiv_data[, turn_integer] <- lapply(hiv_data[, turn_integer], as.integer)


#Check if there are rows where all the medication values are "Other" or "Not Applied"
rows_with_other_or_na <- rowSums(hiv_data[, c("Other_base", "Not_applied_INI", "Not_applied_NNRTI", "Not_applied_extra_pi")] == 1, na.rm = TRUE) == 4

#There are 1069 rows where patients took only the "Other" base drug
sum(rows_with_other_or_na)


```

```{r Data Processing IV}

#Drug classifications

#Nucleoside Reverse Transcriptase Inhibitor (NRTIs):
#FTC (Emtricitabine)
#TDF (Tenofovir Disoproxil Fumarate)
#3TC (Lamivudine)
#ABC (Abacabir)
#TAF (Tenofovir alafenamide)


#Protease Inhibitor (PI):
#DRV (Darunavir)
#RTVB ? (Ritonavir) -> boosted?
#LPV (Lopinavir)
#ATV (Atazanavir)
#RTV -> Pharmacokinetic Enhancer (Ritonavir)


#Integrase Strand Transfer Inhibitor (INSTI):
#EVG (Elvitegravir)
#DTG (Dolutegravir)
#RAL (Raltegravir)


#Non-Nucleoside Reverse Transcriptase Inhibitor (NNRTI):
#NVP (Nevirapine)
#EFV (Efavirenz)
#RPV (Rilpivirine)


#Pharmacokinetic enhancers
#Extra_pk_En



#FTC
#https://clinicalinfo.hiv.gov/en/drugs/emtricitabine/patient


#TDF
#https://clinicalinfo.hiv.gov/en/drugs/elvitegravir-cobicistat-emtricitabine-tenofovir-disoproxil-fumarate/patient

#3TC
#https://clinicalinfo.hiv.gov/en/drugs/lamivudine-zidovudine/patient

#ABC
#https://clinicalinfo.hiv.gov/en/drugs/abacavir/patient

#TAF
#https://clinicalinfo.hiv.gov/en/drugs/darunavir-cobicistat-emtricitabine-tenofovir-alafenamide/patient

#DRV
#https://clinicalinfo.hiv.gov/en/drugs/darunavir-cobicistat-emtricitabine-tenofovir-alafenamide/patient

#RTVB, RTV (Ritonavir)
#https://clinicalinfo.hiv.gov/en/drugs/ritonavir/patient

#########################################################
#Although ritonavir is FDA-approved for the treatment of HIV infection, it is no longer used for its activity against HIV. Instead, ritonavir (given at low doses) is currently used as a pharmacokinetic enhancer to boost the activity of other HIV medicines. -> Pharmacokinetic Enhancer (ritonavir) <-

#HOWEVER, WE WILL TREAT THE MEDICATIONS RTV & RTVB AS PIs#
#########################################################


#EVG (Elvitegravir)
#https://clinicalinfo.hiv.gov/en/drugs/elvitegravir-cobicistat-emtricitabine-tenofovir-alafenamide/patient

#DTG (Dolutegravir)
#https://clinicalinfo.hiv.gov/en/drugs/dolutegravir/patient

#RAL (Raltegravir)
#https://clinicalinfo.hiv.gov/en/drugs/raltegravir/patient


#NVP (Nevirapine)
#https://clinicalinfo.hiv.gov/en/drugs/nevirapine/patient

#EFV (Efavirenz)
#https://clinicalinfo.hiv.gov/en/drugs/efavirenz/patient


#RTV (Rilpivirine)
#https://clinicalinfo.hiv.gov/en/drugs/rilpivirine/patient

#LPV (Lopinavir)
#https://clinicalinfo.hiv.gov/en/drugs/lopinavir-ritonavir/patient

#ATV (Atazanavir)
#https://clinicalinfo.hiv.gov/en/drugs/atazanavir/patient

#RTV (ritonavir)
#https://clinicalinfo.hiv.gov/en/drugs/lopinavir-ritonavir/patient




#Create a new variable `NRTI_Regimen` based on specific columns
hiv_data$NRTI_Regimen <- apply(hiv_data[, c("FTC", "TDF", "TC3", "ABC", "TAF")], 1, function(row) {
  
  #Get column names with 1 values
  nrti_columns <- names(row[row == 1])
  
  #Replace "TC3" with "3TC" in the column names
  nrti_columns <- gsub("TC3", "3TC", nrti_columns)
  
  #Concatenate column names with pluses in between
  regimen <- paste(nrti_columns, collapse = " + ")
  
  #Return the NRTI regimen
  ifelse(regimen == "", "None", regimen)
})


#Create a new variable `PI_Regimen` based on specific columns
hiv_data$PI_Regimen <- apply(hiv_data[, c("DRV_base", "RTVB_base", "DRV_extra_pi", "RTVB_extra_pi", "LPV", "ATV", "RTV")], 1, function(row) {
  
  #Get column names with 1 values
  pi_columns <- names(row[row == 1])
  
  #Replace "DRV_base" with "DRV" in the column names
  pi_columns <- gsub("DRV_base", "DRV", pi_columns)
  
  #Replace "DRV_extra_pi" with "DRV" in the column names
  pi_columns <- gsub("DRV_extra_pi", "DRV", pi_columns)
  
  #Replace "RTVB_base" with "RTVB" in the column names
  pi_columns <- gsub("RTVB_base", "RTVB", pi_columns)
  
  #Replace "RTVB_extra_pi" with "RTVB" in the column names
  pi_columns <- gsub("RTVB_extra_pi", "RTVB", pi_columns)
  
  #De-duplicate pi_columns (as DRV and RTVB may appear more than once)
  pi_columns <- unique(pi_columns)
  
  #Concatenate column names with pluses in between
  regimen <- paste(pi_columns, collapse = " + ")
  
  #Return the NRTI regimen
  ifelse(regimen == "", "None", regimen)
  
})


#Create a new variable `INSTI_regimen` based on specific columns
hiv_data$INSTI_regimen <- apply(hiv_data[, c("EVG", "DTG", "RAL")], 1, function(row) {
  
  #Get column names with 1 values
  insti_columns <- names(row[row == 1])
  
  #Concatenate column names with pluses in between
  regimen <- paste(insti_columns, collapse = " + ")
  
  #Return the NRTI regimen
  ifelse(regimen == "", "None", regimen)
  
})


#Create a new variable `NNRTI_regimen` based on specific columns
hiv_data$NNRTI_regimen <- apply(hiv_data[, c("NVP", "EFV", "RPV")], 1, function(row) {
  
  #Get column names with 1 values
  nnrti_columns <- names(row[row == 1])
  
  #Concatenate column names with pluses in between
  regimen <- paste(nnrti_columns, collapse = " + ")
  
  #Return the NRTI regimen
  ifelse(regimen == "", "None", regimen)
  
})

hiv_data[, c(-9, -10, -11, -12, -13, -14, -15, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30)] -> hiv_data

#Where `extra_pk_En` is missing, turn the regimens into missing as well
hiv_data[is.na(hiv_data$Extra_pk_En), c("NRTI_Regimen", "PI_Regimen", "INSTI_regimen", "NNRTI_regimen")] <- NA


#Change the order of the columns
other_columns <- setdiff(names(hiv_data), c("Extra_pk_En", "PatientID", "Timestep"))

#Rearrange the columns
hiv_data[c(other_columns, c("Extra_pk_En", "PatientID", "Timestep"))] -> hiv_data
  
#Save the processed data frame
write.csv(hiv_data, "processed_data_hiv.csv")

```


```{r Data Processing V}

hiv_data <- read.csv("processed_data_hiv.csv") %>% select(-1)

#Convert VL to float
hiv_data$VL <- as.numeric(hiv_data$VL)

#Convert CD4 to float
hiv_data$CD4 <- as.numeric(hiv_data$CD4)

#Convert Rel_CD4 to float
hiv_data$Rel_CD4 <- as.numeric(hiv_data$Rel_CD4)

#Convert Other_base to factor
hiv_data$Other_base <- as.factor(hiv_data$Other_base)

#Convert NRTI_Regimen to factor
hiv_data$NRTI_Regimen <- as.factor(hiv_data$NRTI_Regimen)

#Convert PI_Regimen to factor
hiv_data$PI_Regimen <- as.factor(hiv_data$PI_Regimen)

#Convert INSTI_regimen to factor
hiv_data$INSTI_regimen <- as.factor(hiv_data$INSTI_regimen)

#Convert NNRTI_regimen to factor
hiv_data$NNRTI_regimen <- as.factor(hiv_data$NNRTI_regimen)

#Convert Extra_pk_En to factor
hiv_data$Extra_pk_En <- as.factor(hiv_data$Extra_pk_En)

#Convert Gender to factor
hiv_data$Gender <- as.factor(hiv_data$Gender)

#Convert Ethnic to factor
hiv_data$Ethnic <- as.factor(hiv_data$Ethnic)


#VL has the biggest amount of missing data, followed by CD4 and Rel_CD4
#md.pattern(hiv_data)


#Get all combinations of variables
hiv_data %>% 
  group_by(Other_base, NRTI_Regimen, PI_Regimen, INSTI_regimen, NNRTI_regimen, Extra_pk_En) %>% 
  count() %>%
  arrange(desc(n)) -> combinations


#######################################################################
#Sort the unique `NRTI_Regimen` values by frequency in descending order
hiv_data$NRTI_Regimen %>% table() -> value_counts
# 3TC + ABC FTC + TAF FTC + TDF      None 
#    122697     13548    271873      7464 

sorted_levels <- names(sort(value_counts, decreasing = TRUE))
hiv_data$NRTI_Regimen <- fct_relevel(hiv_data$NRTI_Regimen, sorted_levels)

#"FTC + TDF", "3TC + ABC", "FTC + TAF", "None" 
levels(hiv_data$NRTI_Regimen) <- c("NRTI:A", "NRTI:B", "NRTI:C", "None")


#######################################################################
#Sort the unique `PI_Regimen` values by frequency in descending order
hiv_data$PI_Regimen %>% table() -> value_counts
          #    ATV              DRV        DRV + ATV        DRV + LPV        DRV + RTV DRV + RTVB + RTV              LPV 
          #   3177            34547             1981               14            12447            37991              307 
          #   None              RTV             RTVB       RTVB + ATV       RTVB + LPV       RTVB + RTV 
          # 304560              313             1522            13267              129             5327 

sorted_levels <- names(sort(value_counts, decreasing = TRUE))
hiv_data$PI_Regimen <- fct_relevel(hiv_data$PI_Regimen, sorted_levels)

#[1] "None"             "DRV + RTVB + RTV" "DRV"              "RTVB + ATV"       "DRV + RTV"        "RTVB + RTV"      
#[7] "ATV"              "DRV + ATV"        "RTVB"             "RTV"              "LPV"              "RTVB + LPV"      
#[13] "DRV + LPV" 
levels(hiv_data$PI_Regimen) <- c("None", "PI:A", "PI:B", "PI:C", "PI:D", "PI:E", "PI:F", "PI:G", "PI:H", 
                                 "PI:I", "PI:J", "PI:K", "PI:L")


#######################################################################
#Sort the unique `INSTI_regimen` values by frequency in descending order
hiv_data$INSTI_regimen %>% table() -> value_counts
 #   DTG    EVG   None    RAL 
 # 93023  29319 283957   9283 

sorted_levels <- names(sort(value_counts, decreasing = TRUE))
hiv_data$INSTI_regimen <- fct_relevel(hiv_data$INSTI_regimen, sorted_levels)

#"None" "DTG"  "EVG"  "RAL"
levels(hiv_data$INSTI_regimen) <- c("None", "INSTI:A", "INSTI:B", "INSTI:C")


#######################################################################
#Sort the unique `NNRTI_regimen` values by frequency in descending order
hiv_data$NNRTI_regimen %>% table() -> value_counts
 #   EFV   None    NVP    RPV 
 # 69665 243982  15230  86705 

sorted_levels <- names(sort(value_counts, decreasing = TRUE))
hiv_data$NNRTI_regimen <- fct_relevel(hiv_data$NNRTI_regimen, sorted_levels)

#"None" "RPV"  "EFV"  "NVP" 
levels(hiv_data$NNRTI_regimen) <- c("None", "NNRTI:A", "NNRTI:B", "NNRTI:C")


#######################################################################
#Sort the unique `Other_base` values by frequency in descending order
hiv_data$Other_base %>% table() -> value_counts
#      0      1 
# 408118   7464 

sorted_levels <- names(sort(value_counts, decreasing = TRUE))
hiv_data$Other_base <- fct_relevel(hiv_data$Other_base, sorted_levels)

#"0" "1" 
levels(hiv_data$Other_base) <- c("None", "Base:Other")


#######################################################################
#Sort the unique `Extra_pk_En` values by frequency in descending order
hiv_data$Extra_pk_En %>% table() -> value_counts
#      0      1 
# 387168  28414 

sorted_levels <- names(sort(value_counts, decreasing = TRUE))
hiv_data$Extra_pk_En <- fct_relevel(hiv_data$Extra_pk_En, sorted_levels)

#"0" "1" 
levels(hiv_data$Extra_pk_En) <- c("None", "Extra_pk_En")

#Create the MICE imputation model
impute_model <- mice(hiv_data, m = 5, seed = 123)

#Save the mice-processed data frames
imputed_data <- complete(impute_model, 1)
write.csv(imputed_data, "processed_data_hiv_1.csv")
imputed_data <- complete(impute_model, 2)
write.csv(imputed_data, "processed_data_hiv_2.csv")
imputed_data <- complete(impute_model, 3)
write.csv(imputed_data, "processed_data_hiv_3.csv")
imputed_data <- complete(impute_model, 4)
write.csv(imputed_data, "processed_data_hiv_4.csv")
imputed_data <- complete(impute_model, 5)
write.csv(imputed_data, "processed_data_hiv_5.csv")

#Tracepolts of our imputed variables
# plot(imp1, "VL", layout = c(2, 1))
# plot(imp1, "CD4", layout = c(2, 1))
# plot(imp1, "Rel_CD4", layout = c(2, 1))
# plot(imp1, "Other_base", layout = c(2, 1))
# plot(imp1, "NRTI_Regimen", layout = c(2, 1))
# plot(imp1, "PI_Regimen", layout = c(2, 1))
# plot(imp1, "INSTI_regimen", layout = c(2, 1))
# plot(imp1, "NNRTI_regimen", layout = c(2, 1))
# plot(imp1, "Extra_pk_En", layout = c(2, 1))

#Stripplots of our imputed variables
#stripplot(impute_model, VL+CD4+Rel_CD4+Other_base+NRTI_Regimen+PI_Regimen+INSTI_regimen+NNRTI_regimen+Extra_pk_En~.imp)


summary(impute_model)


# Class: mids
# Number of multiple imputations:  5 
# Imputation methods:
#            VL           CD4       Rel_CD4        Gender        Ethnic    Other_base 
#         "pmm"         "pmm"         "pmm"            ""            ""      "logreg" 
#  NRTI_Regimen    PI_Regimen INSTI_regimen NNRTI_regimen   Extra_pk_En     PatientID 
#     "polyreg"     "polyreg"     "polyreg"     "polyreg"      "logreg"            "" 
#      Timestep 
#            "" 
#  

```

```{r}

#Read the different CSV files
hiv_1 <- read.csv("C:/Users/emman/OneDrive/Desktop/DATATHON_TEAM_2/Some_preliminary_exploration/processed_data_hiv_1.csv")
hiv_2 <- read.csv("C:/Users/emman/OneDrive/Desktop/DATATHON_TEAM_2/Some_preliminary_exploration/processed_data_hiv_2.csv")
hiv_3 <- read.csv("C:/Users/emman/OneDrive/Desktop/DATATHON_TEAM_2/Some_preliminary_exploration/processed_data_hiv_3.csv")
hiv_4 <- read.csv("C:/Users/emman/OneDrive/Desktop/DATATHON_TEAM_2/Some_preliminary_exploration/processed_data_hiv_4.csv")
hiv_5 <- read.csv("C:/Users/emman/OneDrive/Desktop/DATATHON_TEAM_2/Some_preliminary_exploration/processed_data_hiv_5.csv")

#Remove first column of each data frame
hiv_1 %>% select(-1) -> hiv_1
hiv_2 %>% select(-1) -> hiv_2
hiv_3 %>% select(-1) -> hiv_3
hiv_4 %>% select(-1) -> hiv_4
hiv_5 %>% select(-1) -> hiv_5 

```

```{r}

list.df <- list(hiv_1, hiv_2, hiv_3, hiv_4, hiv_5)
newDF <- do.call(rbind, list.df)
newDF$id <- factor(rep(1:length(list.df), each = sapply(list.df, nrow)))

#Create the ggplot object and specify the aesthetic mappings
other_base_plot <- ggplot(newDF, aes(x = Other_base, fill = id)) + 
  geom_bar(position = "dodge", colour = "black")
NRTI_regimen_plot <- ggplot(newDF, aes(x = NRTI_Regimen, fill = id)) + 
  geom_bar(position = "dodge", colour = "black")
PI_regimen_plot <- ggplot(newDF, aes(x = PI_Regimen, fill = id)) + 
  geom_bar(position = "dodge", colour = "black")
INSTI_regimen_plot <- ggplot(newDF, aes(x = INSTI_regimen, fill = id)) + 
  geom_bar(position = "dodge", colour = "black")
NNRTI_regimen_plot <- ggplot(newDF, aes(x = NNRTI_regimen, fill = id)) + 
  geom_bar(position = "dodge", colour = "black")
Extra_pk_En_plot <- ggplot(newDF, aes(x = Extra_pk_En, fill = id)) + 
  geom_bar(position = "dodge", colour = "black")

#Inspect the plots
other_base_plot + NRTI_regimen_plot + INSTI_regimen_plot + 
  NNRTI_regimen_plot + Extra_pk_En_plot
PI_regimen_plot


VL_plot <-  ggplot(newDF, aes(x = VL, colour = factor(id)))+ 
  geom_density(alpha = 0.1, fill = "transparent", position = "dodge")
CD4_plot <-  ggplot(newDF, aes(x = CD4, colour = factor(id)))+ 
  geom_density(alpha = 0.1, fill = "transparent", position = "dodge")
Rel_CD4_plot <-  ggplot(newDF, aes(x = Rel_CD4, colour = factor(id)))+ 
  geom_density(alpha = 0.1, fill = "transparent", position = "dodge")

#Inspect the plots
VL_plot + CD4_plot + Rel_CD4_plot  

```

```{r}

hiv_averaged <- data.frame(empty = rep("", 534960))

#Columns to process
columns <- names(hiv_1)[c(-4, -5, -12, -13)]

# Iterate over each column
for (col in columns) {
  #Extract values from each data frame
  values <- cbind(hiv_1[, col], hiv_2[, col], hiv_3[, col], hiv_4[, col], hiv_5[, col])
  
  #Randomly select a value from each row
  random_values <- apply(values, 1, sample, size = 1)
  
  hiv_averaged <- cbind(hiv_averaged, random_values)
  
  colnames(hiv_averaged)[ncol(hiv_averaged)] <- col
}

#Remove empty
hiv_averaged %>% select(-1) -> hiv_averaged

hiv_averaged <- cbind(hiv_averaged, hiv_1['Gender'])
colnames(hiv_averaged)[10] <- 'Gender'

hiv_averaged <- cbind(hiv_averaged, hiv_1['Ethnic'])
colnames(hiv_averaged)[11] <- 'Ethnic'


hiv_averaged <- cbind(hiv_averaged, hiv_1['PatientID'])
colnames(hiv_averaged)[12] <- 'PatientID'
  
hiv_averaged <- cbind(hiv_averaged, hiv_1['Timestep'])
colnames(hiv_averaged)[13] <- 'Timestep'

write.csv(hiv_averaged, 
          "C:/Users/emman/OneDrive/Desktop/DATATHON_TEAM_2/Some_preliminary_exploration/imputed_random_hiv.csv")



```


```{r}

hiv_data <- read.csv("imputed_random_hiv.csv")

#Concatenate the factor vectors with pluses in between, excluding NAs and "None"
concatenated_medicine <- sapply(1:length(hiv_data$NRTI_Regimen), function(i) {
  values <- c(hiv_data$NRTI_Regimen[i], hiv_data$PI_Regimen[i], hiv_data$INSTI_regimen[i],
              hiv_data$NNRTI_regimen[i], hiv_data$Other_base[i], hiv_data$Extra_pk_En[i])
  values <- values[values != "None"]
  if (length(values) > 0) {
    paste(values, collapse = "+")
  } else {
    "None"
  }
})

#There are 258 rows with patients that had "None" for medications - after the multiple imputation
#According to the original data, all patients had some sort of medication 
#(except for the missing values - we assume these did not have their medication data recorded)

#Thus, we shall remove these 258 rows
sum(concatenated_medicine == "None")

hiv_data %>% select(c(-1, -5, -6, -7, -8, -9, -10)) %>% mutate("Medications_Regime" = concatenated_medicine) -> hiv_data

hiv_data$Medications_Regime <- as.factor(hiv_data$Medications_Regime)

#nrow(hiv_data) #534960

hiv_data[hiv_data$Medications_Regime != "None", ] -> hiv_data

#nrow(hiv_data) #534702

write.csv(hiv_data, "final_hiv.csv")

```

#######################
DATA HAS BEEN PROCESSED
#######################


########
Remove VL under 200 at the start?

Focus on top medication regimens (i.e., code all the bottom regimens are 'other' for instance)
########


